### ISSUE TITLE
docker-compose build error

### ISSUE THREAD

**Issue by Dalospacsirta** [boonisz/cachet-url-monitor-dc#1]
Hello!
I'm trying to run your web service in docker but i got error:
`ERROR: Named volume "monitor-config.yml:/usr/src/app/config/config.yml:rw" is used in service "monitor" but no declaration was found in the volumes section.`
My folder structure:
├── cachet
│   ├── CHANGELOG.md
│   ├── conf
│   │   ├── nginx.conf
│   │   ├── nginx-site.conf
│   │   ├── php-fpm-pool.conf
│   │   └── supervisord.conf
│   ├── CONTRIBUTING.md
│   ├── docker-compose.yml
│   ├── Dockerfile
│   ├── entrypoint.sh
│   ├── LICENSE
│   ├── Makefile
│   ├── openshift
│   │   ├── cachethd-dc.yaml
│   │   └── README.md
│   ├── README.md
│   ├── release-helper.sh
│   └── test
│       ├── docker-compose-mysql.yml
│       ├── docker-compose-sqlite.yml
│       ├── docker_helpers.bash
│       ├── lib
│       │   ├── batslib.bash
│       │   └── output.bash
│       ├── test.full.bats
│       ├── test_helpers.bash
│       ├── test.mysql.bats
│       └── test.sqlite.bats
├── cachet-url-monitor
│   ├── cachet_url_monitor
│   │   ├── client.py
│   │   ├── configuration.py
│   │   ├── exceptions.py
│   │   ├── expectation.py
│   │   ├── __init__.py
│   │   ├── latency_unit.py
│   │   ├── plugins
│   │   │   ├── __init__.py
│   │   │   └── token_provider.py
│   │   ├── scheduler.py
│   │   ├── status.py
│   │   └── webhook.py
│   ├── config.yml
│   ├── dev_requirements.txt
│   ├── Dockerfile
│   ├── LICENSE
│   ├── README.md
│   ├── requirements.txt
│   ├── setup.cfg
│   ├── setup.py
│   ├── tests
│   │   ├── configs
│   │   │   ├── config_invalid_type.yml
│   │   │   ├── config_multiple_urls.yml
│   │   │   ├── config_webhooks.yml
│   │   │   └── config.yml
│   │   ├── plugins
│   │   │   └── test_token_provider.py
│   │   ├── test_client.py
│   │   ├── test_configuration.py
│   │   ├── test_expectation.py
│   │   ├── test_latency_unit.py
│   │   └── test_scheduler.py
│   └── tox.ini
├── docker-compose.yml
├── monitor-config.yml
└── README.md

**Comment by Dalospacsirta** [comment]
Change from:
```
    volumes:
      - monitor-config.yml:/usr/src/app/config/config.yml
  ```
  to:
```
  volumes:
      - .monitor-config.yml:/usr/src/app/config/config.yml
```

This work!

**Comment by boonisz** [comment]
Thanks for the bug fix.
Effectively, without the dot, docker-compose will use docker volume instead of local file.
I will integrate your solution.
Regards :)
